### ISSUE TITLE
adding second item

### ISSUE THREAD

**Issue by TetroYT** [tim03we/LobbySystem#1]
how do i add a second item in the config

items:
  - 4-0-1-4-§bSkyBlock-skyblock

i tried copying and pasting and changing the number 4 to 5 but it stayed the same

**Comment by tim03we** [comment]
items:
	- 4-0-1-4-§bSkyBlock-skyblock
	- 4-0-1-4-§bSkyBlock-skyblock
I still have to fix the fact that you can use several items. Just wait until tonight.

**Comment by TetroYT** [comment]
oh ok thanks

**Comment by tim03we** [comment]
Just stop by the discord. :P Then you can see when I fixed it. https://discord.gg/z8utTM8

**Comment by tim03we** [comment]
Fixed now!
